import Head from 'next/head';
// import Image from 'next/image';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wheather - Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='border-b-4 border-red-500'>Test</h1>
    </div>
  )
}
